name: Download Docker Image
on:
  workflow_dispatch:  # 手动触发

jobs:
  download-image:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker
      uses: docker/setup-buildx-action@v3
      
    - name: Pull and save Docker image
      run: |
        docker pull --platform linux/arm64 openjdk:8-jdk-alpine3.9
        docker save -o jdk8-arm.tar openjdk:8-jdk-alpine3.9
        ls -lh jdk8-arm.tar
        
    - name: Upload image artifact
      uses: actions/upload-artifact@v4
      with:
        name: jdk-image
        path: jdk8-arm.tar
        retention-days: 7
